-- 1. What are the details of all cars purchased in the year 2022?
select 
  c.make, 
  c.type, 
  c.style, 
  c.cost_$ as cost_in_$, 
  year(s.purchase_date) as year_purchased 
from 
  cars c 
  inner join sales s on c.car_id = s.car_id 
where 
  year(s.purchase_date) = 2022 
order by 
  cost_in_$ desc;

-- 2. What is the total number of cars sold by each salesperson?
select 
  sales.salesman_id, 
  salespersons.name, 
  count(sales.car_id) as total_car_sold 
from 
  sales 
  inner join salespersons using(salesman_id) 
group by 
  sales.salesman_id, 
  salespersons.name 
order by 
  sales.salesman_id;

-- 3. What is the total revenue generated by each salesperson?
select 
  s.salesman_id, 
  sp.name, 
  sum(cost_$) as revenue_generated 
from 
  sales s 
  inner join salespersons sp using(salesman_id) 
  inner join cars c using(car_id) 
group by 
  s.salesman_id, 
  sp.name 
order by 
  s.salesman_id;

-- 4. What are the details of the cars sold by each salesperson?
SELECT 
  sales.salesman_id, 
  salespersons.name, 
  cars.car_id, 
  cars.make, 
  cars.type, 
  cars.style, 
  cars.cost_$ 
FROM 
  sales 
  INNER JOIN salespersons USING(salesman_id) 
  INNER JOIN cars USING(car_id) 
GROUP BY 
  sales.salesman_id, 
  salespersons.name, 
  cars.car_id 
ORDER BY 
  sales.salesman_id, 
  cars.car_id;
  
-- 5. What is the total revenue generated by each car type?
select 
  sales.car_id, 
  cars.type, 
  sum(cars.cost_$) as cost_per_type 
from 
  sales 
  inner join cars using(car_id) 
group by 
  sales.car_id, 
  cars.type 
order by 
  sales.car_id;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select 
  c.car_id, 
  c.make, 
  c.type, 
  c.style, 
  c.cost_$, 
  s.salesman_id, 
  sp.name, 
  year(s.purchase_date) as purchase_year 
from 
  cars c 
  inner join sales s using(car_id) 
  inner join salespersons sp using(salesman_id) 
where 
  year(s.purchase_date)= 2021 
  and name = 'Emily Wong';
  
-- 7. What is the total revenue generated by the sales of hatchback cars?
select 
  s.car_id, 
  c.style, 
  sum(c.cost_$) as total_revenue 
from 
  sales s 
  inner join cars c using(car_id) 
where 
  c.style = "Hatchback" 
group by 
  s.car_id;
  
-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select 
  sum(total_revenue) as Total_revenue 
from 
  (
    SELECT 
      s.car_id, 
      c.style, 
      sum(c.cost_$) as total_revenue 
    from 
      sales s 
      inner join cars c using(car_id) 
    where 
      c.style = "SUV" 
      and year(s.purchase_date)= 2021 
    group by 
      s.car_id, 
      c.style
  ) as T;
  
-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select 
  s.salesman_id, 
  sp.name, 
  sp.city, 
  count(s.car_id) as total_car_sold 
from 
  sales s 
  inner join salespersons sp using (salesman_id) 
where 
  year(s.purchase_date)= 2023 
group by 
  s.salesman_id, 
  sp.name 
order by 
  count(s.car_id) desc 
limit 
  1;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select 
  s.salesman_id, 
  sp.name, 
  sp.age, 
  sum(cars.cost_$) as total_revenue 
from 
  sales s 
  inner join salespersons sp using(salesman_id) 
  inner join cars using(car_id) 
where 
  year(s.purchase_date)= 2022 
group by 
  s.salesman_id, 
  sp.name 
order by 
  sum(cars.cost_$) desc 
limit 
  1;

-- ------------------------------------------------------------- THE END -------------------------------------------------------------------------------